### ISSUE TITLE
无法在whitelist.js之外的域名调用bilibili new player

### ISSUE THREAD

**Issue by at-wr** [MonianHello/BiliBiliVideoPlayerParameters#1]
如题，无法在whitelist.js之外的域名调用bilibili new player
whitelist.js 链接: https://s1.hdslb.com/bfs/static/player/main/whitelist.js?ver=20220315

**Comment by Barry-Flynn** [comment]
是的，新版编辑器好像做了 Referrer 匹配，只有白名单内的域名可以正常加载。这个编辑器应该是用来作为B站活动页的内嵌元素的，因为可以弹幕、清晰度等功能都是正常的。`https://www.bilibili.com/blackboard/newplayer.html?bvid=BV1Ty4y1Y7Mw&danmaku=0&autoplay=0`

相反，官方给的内嵌播放器除了播放按钮，点击其他任何元素都会跳转到原视频页面，对比YouTube显得有些小气了，甚至不如国内的爱优腾和西瓜视频。`https://player.bilibili.com/player.html?bvid=BV1Ty4y1Y7Mw&danmaku=1&autoplay=0`
